neurobagel/documentation

- .github/workflows/cd.yaml
> Added and configured cd workflow

- docs/dictionaries.md
Closes #14 
- Updated possible heuristics
> Updated possible heuristics

- docs/CNAME
Added CNAME file to not break custom domain on mkdocs update
See also: https://github.com/mkdocs/mkdocs/issues/1257
For new features:
For bug fixes:
> [FIX] add CNAME file for custom domain

- docs/infrastructure.md
Closes #56
- Environment variables table updated to be synced with https://github.com/neurobagel/api/blob/main/README.md
- Variable name typos fixed
- Updated links
> [ENH] Update instructions for setting up a graph

- docs/api_environment_variables.tsv
- docs/infrastructure.md
- mkdocs.yml
- requirements.txt
Closes #63 
- Updated sysadmin instructions to be synced with current API [README](https://github.com/neurobagel/api/blob/main/README.md)
- Moved API environment variables into separate TSV for easier editing (e.g., if new variables need to be added following https://github.com/neurobagel/api/pull/154)
> [ENH] Document configurable origins and move environment variables into TSV

- docs/overview.md
- mkdocs.yml
> [ENH] Add search bar and link to our Docker Hub profile

- docs/dictionaries.md
- docs/graph_data.md
Closes #81 
- Fixed broken links in `dictionaries.md` and `graph_data.md`
- Turned the tip box containing examples in `dictionaries.md` to an example box and moved it into the overview section
> [FIX] Fixed broken links

- docs/dictionaries.md
- docs/term_naming_standards.md
Closes #87
See also https://github.com/neurobagel/bagel-cli/issues/139
> [FIX] Update namespace for healthy control terms

- docs/infrastructure.md
> [FIX] Delete erroneous spaces in user credentials provided using curl

- docs/annotation_tool.md
- docs/dictionaries.md
> [MNT] Capitalized age heuristics

- docs/api.md
- docs/dictionaries.md
Closes #26
- also fixes some link formatting problems
> [ENH] Add examples of age values per heuristic

- docs/nipoppy/overview.md
> [MNT] Update links to dashboard following app rename

- docs/federate.md
> [ENH] Update federation instructions to use JSON local nodes config file

- docs/federate.md
> [FIX] Update local federation setup examples to not use `localhost`

- docs/api.md
- docs/federate.md
- docs/infrastructure.md
- docs/overview.md
- docs/query_tool.md
- mkdocs.yml
- Closes #140
- Closes #150
- Closes #153
> [REF] Switch to GraphDB defaults and better differentiate Neurobagel APIs

- docs/nipoppy/configs.md
> remove `bids_id` column from manifest

- docs/nipoppy/workflow/bids_conv.md
- docs/nipoppy/workflow/dicom_org.md
Closes #154.
- Fix wrong paths to `<DATASET_ROOT>/scratch/raw_dicom`
> [FIX] Change `raw_dicoms` -> `raw_dicom` in Nipoppy docs

- docs/infrastructure.md
- Closes #137
- Includes docs changes for https://github.com/neurobagel/recipes/issues/16
Other changes proposed in this pull request:
- "Get a license" section removed, contents merged with graph database intro
- Minor reordering/reformatting for easier reading
> [FIX] Update notes on environment variables + other minor fixes

- docs/federate.md
- docs/infrastructure.md
Closes #116 
Other changes proposed in this pull request:
- Standardized names of `.env` files to use in local deployments for simplicity
- Fixed example for `API_QUERY_URL` in local federation
- Provide node name examples with spaces
> [ENH] Update local node and local federation setup instructions

- docs/contributing/CONTRIBUTING.md
- docs/contributing/pull_requests.md
- docs/contributing/team.md
- mkdocs.yml
Closes #171 
- New sections:
- "Identifying an issue to work on"
- "Making a change"
- "Have a question about contributing?"
- Updated sections:
- "Pull request guidelines"
- "Pull request reviews"
- `pull_requests.md` -> `CONTRIBUTING.md`
> [ENH] Expand contributing guidelines 🥳

- .github/pull_request_template.md
Note that this template is unique to this repo as the PR prefixes we suggest + checklist are slightly different than for non-documentation repos
> [FIX] Fix dead link in pull_request_template.md

- docs/infrastructure.md
- Closes #169
- Closes #177 
- Closes #178
> [ENH] Document GraphDB setup script and other setup clarifications

- docs/federate.md
- docs/infrastructure.md
- docs/query_tool.md
- mkdocs.yml
- requirements.txt
- Closes #179 
- `API_QUERY_URL` replaced by `NB_API_QUERY_URL`
- Using [mkdocs-include-markdown-plugin](https://github.com/mondeja/mkdocs-include-markdown-plugin), query tool documentation page contents replaced by link to query tool [README](https://github.com/neurobagel/query-tool/blob/main/README.md) sections where appropriate for easier syncing
> [FIX] Update environment variable name and link to query tool README

- docs/overrides/home.html
- Closes #
This makes the docs page use visible in plausible
> [MNT] Add the plausible script to the website

- docs/query_tool.md
> [REF] Update the example query results

- .gitignore
- README.md
- docs/overrides/home.html
- docs/overrides/main.html
- docs/stylesheets/output.css
- docs/stylesheets/tailwind.css
- mkdocs.yml
- package-lock.json
- package.json
- postcss.config.js
- tailwind.config.js
Get rid of CDN dependency
- Closes #55
-
-
> [ENH] Correctly embed tailwind into the site

- docs/maintaining.md
> [FIX] Fix a dead link in maintaining

- docs/overrides/home.html
> [FIX] Updated `Get Started` button link

- README.md
- Closes #https://github.com/neurobagel/planning/issues/200
-
-
> [ENH] Add consistent badges

- docs/user_guide/index.md
> [REF] Update links to legacy annotation tool repo

- docs/overrides/home.html
> [FIX] Broken link on overrides page

- docs/contributing/CONTRIBUTING.md
- docs/user_guide/config.md
- mkdocs.yml
- requirements.txt
- Closes #274 
- Update reverse proxy `docker-compose.yml` examples to match latest https://github.com/neurobagel/recipes
- Simplify instructions and formatting for code snippets
- Indent reverse proxy recipe tabs to match corresponding numbered step for readability
- Upgrade minimum `mkdocs-material` version to support more readable tab links
- Fix some broken relative section links (we may have missed the mkdocs warnings)
- our md link checker might not have caught this because the non-functional relative links just don't go anywhere
> [MNT] Update reverse proxy recipes

- docs/user_guide/annotation_tool.md
bootstrap vue is dead
- Closes #
-
-
> [FIX] remove dead link

- docs/user_guide/getting_started.md
- Closes https://github.com/neurobagel/recipes/issues/124
> [ENH] Add note on compatible GraphDB image tag for ARM-based machines

- .pre-commit-config.yaml
- docs/data_models/dictionaries.md
- docs/data_models/variables.md
- docs/user_guide/annotation_tool.md
- docs/user_guide/cli.md
- md_link_check_config.json
- Closes #295 
**NOTE:** The [annotation tool docs](https://neurobagel.org/user_guide/annotation_tool/) still contain references to the `Transformation` annotation, but this page is expected to be rewritten as part of #296 to match the new annotation tool (https://github.com/neurobagel/annotation-tool).
> [ENH] Rename `Transformation` to `Format` on data dictionary page

- docs/user_guide/config.md
- Closes #305
- Related to #306
- Remove reference docs on "Manually setting up a Neurobagel graph backend" to avoid confusion with automated setup scripts
- Provide clearer context and instructions on changing default GraphDB user credentials and security variables
> [REF] Remove deprecated manual GraphDB setup section and clarify credentials updating
