neurobagel/documentation

- docs/datamodels.md
- docs/dictionaries.md
- docs/term_naming_standards.md
On the data dictionaries page, prefixes have been kept for now since the `@context` with URIs is shown as well.
Closes #5
> Align data model/dictionary descriptions and examples with new naming standards

- docs/term_naming_standards.md
- mkdocs.yml
In https://github.com/neurobagel/documentation/pull/9 which added the controlled term naming standards page to encarta, I was silly and forgot to add the new page to the navigation in `mkdocs.yml`. This PR makes the page visible and also updates the page/nav titles slightly for consistency.
For new features:
For bug fixes:
> [DOC] add term naming standards page to nav & update page title

- docs/infrastructure.md
- docs/updating_dataset.md
- mkdocs.yml
Closes #52 
Closes #24
Closes #20 
- Add instructions to use `add_data_to_graph.sh` to upload + update datasets in graph
- Add new page describing steps to regenerate JSONLD files when a dataset has been updated
- Add recommendation for where to keep `.jsonld` outputs created by the CLI for multiple datasets
- Used clearer language to describe database admin vs. user
> [ENH] Update instructions for graph data(base) management

- docs/query_tool.md
- mkdocs.yml
Closes #27
**NOTE: Checks expected to fail until https://github.com/neurobagel/neurobagel_examples/pull/7 is merged**
- New section "Downloading query results" added to query tool page, which contains the contents of https://github.com/neurobagel/documentation/wiki/Query-Tool with some minor edits for clarity
- Import example query tool results TSVs (see https://github.com/neurobagel/neurobagel_examples/pull/7) to render as markdown tables
> [ENH] Document query tool result TSVs

- docs/nipoppy/workflow/proc_pipe/mriqc.md
> Remove dead link to Dockerfile from Nipoppy MRIQC page

- docs/infrastructure.md
Closes #80 
Changes proposed in this PR:
- Standardize syntax highlighting on graph setup page
- Fix typo in environment variable name
- Recommend explicitly setting `NB_RETURN_AGG` and `NB_API_ALLOWED_ORIGINS` for extra transparency
- Standardize example db name in Stardog setup steps
> [FIX] Fixed typo and improved consistency in setup instructions

- docs/nipoppy/workflow/dicom_org.md
Closes #
- Fixes broken link that causes CI to fail in #105
-
> [FIX] Fix broken link after renaming `check_dicom_status.py` -> `update_doughnut.py`

- docs/infrastructure.md
- docs/nipoppy/workflow/dicom_org.md
Correction suggestions related to local deployment of Neurobagel :
- remove spurious trailing space which breaks multi-line command,
- add graphDB specific command example,
> [FIX] Correction suggestions related to local deployment of Neurobagel using graphDB

- docs/infrastructure.md
- docs/query_tool.md
> [ENH] Added a subsection for participant-level results tsv in aggregate mode

- docs/infrastructure.md
Closes #103
Closes #76
- Add backend-specific instructions for using `add_data_to_graph.sh`
- Add `curl` commands to check size of graph db
- Add tip for granting script execution permissions
- To make key setup instructions easier to find, move extra info/tips into (collapsible) admonitions where appropriate
- Minor typo fixes/clarifications
> [ENH] Flesh out backend-specific data upload instructions + move extra info into admonitions

- docs/infrastructure.md
- Explicitly provide a sensible path to use for `NB_GRAPH_ROOT_HOST` that is specific to the GraphDB deployment (previously, the container would default to using `stardog_root` for both backends since we don't instruct users to change the path for GraphDB)
> [FIX] Recommend to change `NB_GRAPH_ROOT_HOST` for GraphDB

- docs/infrastructure.md
We don't want to clear the existing data in the graph when we add the vocabulary file!! 😱
> [FIX] Remove `--clear-data` flag from vocab file upload command

- docs/cli.md
- docs/dictionaries.md
- docs/updating_dataset.md
> [ENH] Update info on assessment availability and following data model updates

- docs/contributing/pull_requests.md
Closes #108
See also https://github.com/neurobagel/.github/pull/7
> [ENH] Clarify PR merging responsibility

- docs/infrastructure.md
To better differentiate from our own API
- Closes https://github.com/neurobagel/api/issues/121
-
-
> [REF] rename graph API to backend endpoint

- .github/ISSUE_TEMPLATE/doc_request.yml
- docs/getting_help.md
> [ENH] Document how to give feedback on documentation and add issue template

- docs/cli.md
- Instructions on CLI docs page now brought up to date with most recent set of instructions on repo
> [ENH] Update instructions for CLI dev environment setup

- docs/nipoppy/configs.md
Closes #151.
- Add `"ses-"` prefix to sessions under `"SESSIONS"` key in example `global_configs.json` file
> [FIX] Add "ses-" prefix to sessions in Nipoppy configs page

- docs/infrastructure.md
- mkdocs.yml
- See https://github.com/neurobagel/recipes/issues/12
- **For reviewer: to avoid merging with failing checks, ensure https://github.com/neurobagel/recipes/issues/14 is merged first**
> [REF] Update link to environment variables TSV

- docs/infrastructure.md
Because of https://github.com/neurobagel/recipes/pull/13 we now default to using graphDB syntax. This updates the docs to show the new behaviour
Closes https://github.com/neurobagel/recipes/issues/3
- update examples of `add_data_to_graph.sh` to comply with changes in https://github.com/neurobagel/recipes/pull/13
> [REF] update syntax for data upload script

- docs/overrides/home.html
- docs/overrides/partials/integrations/analytics/plausible.html
- mkdocs.yml
This is the correct implementation
see: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#custom-site-analytics-mkdocsyml
- Replace the (incorrect) embedding of plausible in the home page override with the correct embedding
- see https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#custom-site-analytics-mkdocsyml for docs
- also see https://plausible.neurobagel.org/neurobagel.org to note that the visited pages now show up
> [REF] Integrate plausible via partials

- docs/nipoppy/cli_note.md
- docs/nipoppy/code_org.md
- docs/nipoppy/configs.md
- docs/nipoppy/data_org.md
- docs/nipoppy/glossary.md
- docs/nipoppy/installation.md
- docs/nipoppy/overview.md
- docs/nipoppy/trackers.md
- docs/nipoppy/workflow/bids_conv.md
- docs/nipoppy/workflow/dicom_org.md
- docs/nipoppy/workflow/proc_pipe/fmriprep.md
- docs/nipoppy/workflow/proc_pipe/mriqc.md
- Closes #192 
- Added a "Note" block at the top of every Nipoppy page, for example:
> [ENH] Add top-level note in Nipoppy pages about new Read the Docs website 

- docs/config.md
- docs/getting_started.md
- docs/query_tool.md
> [ENH] Explain how to create a secure password

- .pre-commit-config.yaml
- requirements.txt
- Closes #190 
- Added `codespell` and `markdown-link-check` to `pre-commit` config file
> [MNT] Added `pre-commit` to the repo

- docs/api.md
- docs/cli.md
- docs/data_prep.md
- Closes #208 
- Closes #209
- Closes #212
- Related: https://github.com/neurobagel/documentation/issues/182
> [ENH] Document short CLI option names, subject ID case sensitivity, and strict trailing slash handling

- docs/overrides/home.html
- docs/stylesheets/custom.css
- mkdocs.yml
- Closes #203 
- This PR fixes the problem where tailwind was being made to override mkdocs styles on docs pages other than the homepage, which was resulting in disrupted formatting for mkdocs material elements and text.
> [FIX] Apply tailwind stylesheet just in home.html

- docs/getting_help.md
- docs/maintaining.md
- md_link_check_config.json
- Closes #220 
- Slight restructuring of "Getting Help" page based on type of question
- Explain how to find semver for a `latest` Neurobagel image
- Remove outdated note about needing to manually update data in the graph before restarting services (happens automatically as of https://github.com/neurobagel/recipes/pull/57)
> [ENH] Add Discord link and mention semver label in `latest` images

- docs/config.md
- docs/getting_started.md
- docs/maintaining.md
- Docs update following https://github.com/neurobagel/recipes/pull/86 and https://github.com/neurobagel/recipes/pull/84
- Default profile changed to `full_stack`
- Added instructions for using `COMPOSE_PROFILES` var in .env
- Updated instructions for changing admin/user passwords using .txt files
> [ENH] Update instructions for changing passwords and the default deployment profile

- docs/config.md
- docs/getting_started.md
- docs/maintaining.md
- docs/public_nodes.md
- md_link_check_config.json
- Closes #232 
- Closes #231 
This PR also fixes some links and updates the Markdown Link Check to ignore some non-dereferenceable URLs.
> [MNT] Warn against having local f-API address in `local_nb_nodes.json`, link fixes

- docs/config.md
- docs/getting_started.md
- docs/maintaining.md
- Closes #239 
- Add new section "Behind a proxy" with example docker-compose.yml including NGINX+ACME
- Restructure "Updating data in the graph" section slightly, and link to it more explicitly in the Getting Started steps, to further centralize and make intuitive the key steps for setting up a database. This:
- avoids the complexity of having to link to both https://neurobagel.org/getting_started/#the-neurobagel-node-deployment-recipe and https://neurobagel.org/maintaining/#updating-the-data-in-your-graph whenever we want to refer to a complete node setup (e.g., in this PR, following the old structure, it was difficult to tie in the customized NGINX docker-compose.yml back to the rest of the node setup steps without having to reference multiple …
> [ENH] Add example config for deploying a node behind NGINX and clarify data uploading

- docs/user_guide/query_tool.md
- md_link_check_config.json
- Closes #244 
- Related neurobagel/neurobagel_examples#45
- Update "Downloading query tool results" section to reflect new query result TSVs
- Move example result TSVs into expandable admonitions
- Switch to tables for column descriptions (for reviewer: thoughts on storing these in TSVs in this repo?)
- Update section on aggregate query results to clarify possibility of both aggregate and subject-level data in a query result TSV
TODO: Confirm that query result TSVs look correct in preview after neurobagel/neurobagel_examples#45 is merged
> [ENH] Document descriptive and machine-optimized query result TSVs

- docs/data_models/dictionaries.md
- docs/data_models/term_naming_standards.md
- docs/overrides/home.html
> [MNT] Replace Cognitive Atlas with SNOMED CT as the vocab for assessments

- docs/user_guide/config.md
To have longer request timeouts
- Closes https://github.com/neurobagel/recipes/pull/97
- 
- mounts new config file from recipes (see https://github.com/neurobagel/recipes/pull/100)
- don't merge before the recipe submodule is updated after the linked PR is merged
-
> [ENH] Update reverse proxy recipe with nginx conf

- docs/user_guide/config.md
- Closes #263 
- Added `docker-compose.yml` to configure caddy as a reverse proxy.
- Added an example `Caddyfile`.
> [DOC] Added docker-compose.yml to configure caddy as a reverse proxy

- .github/dependabot.yml
- .github/workflows/cd.yaml
- Addresses failing `cd.yaml` workflow https://github.com/neurobagel/documentation/actions/runs/13647113378/job/38147902467 due to using a deprecated version of `actions/cache`
- See also https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/
> [FIX] Upgrade `actions/cache` and add Dependabot for version updates

- docs/data_models/dictionaries.md
- Related to https://github.com/neurobagel/bagel-cli/pull/437
- Remove use of word "heuristic" from description of age column to reduce confusion/complexity around terms
> [ENH] Add `nb:FromRange` to list of available age transformations

- docs/glossary.md
- docs/user_guide/data_prep.md
- Closes #289
- Clarify and expand on requirements for Neurobagel-compatible phenotypic TSV files
- Add a glossary section for TSV files with standard formatting conventions
> [ENH] More detailed requirements for the phenotypic TSV
